In [3]:
import numpy as np

## Vector Operations

In [22]:
u = np.array([2,4,5,6])

In [21]:
def vec_op(u):
    result = 2 + u
    return result


In [23]:
vec_op(u)

array([4, 6, 7, 8])

## Multiplication

In [ ]:
# vector vector multiplication

v = np.array([1,1,2,0])



In [2]:
def vec_vec_mul(u,v):
    assert u.shape[0] == v.shape[0]
    
    n = u.shape[0]
    
    result=0.0
    
    for i in range(n):
        result = result + u[i]*v[i]
        
    return result

In [5]:
vec_vec_mul(u,v)

np.float64(16.0)

In [6]:
u.dot(v)

np.int64(16)

In [7]:
# Matrix vector multiplication

U = np.array([
    [2,4,5,6],
    [1,2,1,2],
    [3,1,2,1]
])

In [8]:
def mat_vec_mul(U,v):
    assert U.shape[1]==v.shape[0]
    
    num_rows=U.shape[0]
    
    result = np.zeros(num_rows)
    
    for i in range(num_rows):
        result[i] = vec_vec_mul(U[i], v)
        
    return result

In [9]:
mat_vec_mul(U,v)

array([16.,  5.,  8.])

In [10]:
#Matrix Matrix multiplication


V = np.array([
    [1,1,2],
    [0,0.5,1],
    [0,2,1],
    [2,1,0]
]) 

In [11]:
def mat_mat_mul(U,V):
    assert U.shape[1]==V.shape[0]
    
    num_rows = U.shape[0]
    num_cols = V.shape[1]
    
    result = np.zeros((num_rows, num_cols))
    
    for i in range(num_cols):
        vi = V[:, i]
        Uvi = mat_vec_mul(U, vi)
        result[: ,i] = Uvi
        
    return result

In [12]:
mat_mat_mul(U,V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

## Identity matrix

In [ ]:
I = np.eye(3)

I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [15]:
V.dot(I)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

## Matrix Inverse

In [ ]:
Vs= V[[0,1,2]]   #making a sqr matrix
Vs

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [17]:
Vs_inv = np.linalg.inv(Vs)
Vs_inv            #inverse of the matrix

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

##  A x A⁻¹ = Identity Matrix

In [ ]:
Vs_inv.dot(Vs)  

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])