In [1]:
import numpy as np

## Creating Arrays

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
np.full(10,3)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [7]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [9]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [11]:
np.linspace(0,100,11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

## Multidimensional Arrays

In [13]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [15]:
n = np.array([[1,2,3],[4,5,6]])

In [16]:
n[1,2]

np.int64(6)

In [17]:
n

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
n[0]=[7,8,9]
n

array([[7, 8, 9],
       [4, 9, 6]])

In [21]:
n[:,2]=[6,9]
n

array([[7, 8, 6],
       [4, 9, 9]])

## Randomly generated Arrays

In [ ]:
np.random.seed(2)
np.random.rand(5,2)  #use Uniform Distribution

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [ ]:
np.random.seed(2)
np.random.randn(5,2)  #use Standard Distribution

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [27]:
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5,2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]], dtype=int32)

## Element-wise operations

In [28]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [39]:
b=10+a
b

array([10, 11, 12, 13, 14])

In [31]:
a-2

array([-2, -1,  0,  1,  2])

In [34]:
c = (10+(a*2))**2/100
c

array([1.  , 1.44, 1.96, 2.56, 3.24])

## Comparision Operator

In [37]:
a

array([0, 1, 2, 3, 4])

In [38]:
a>=2

array([False, False,  True,  True,  True])

In [40]:
b

array([10, 11, 12, 13, 14])

In [41]:
a>b

array([False, False, False, False, False])

In [44]:
a[a<b]

array([0, 1, 2, 3, 4])

## Summarizing operations

In [45]:
a

array([0, 1, 2, 3, 4])

In [46]:
a.mean()

np.float64(2.0)

In [47]:
a.std()

np.float64(1.4142135623730951)

In [49]:
np.min(a)

np.int64(0)